name: CI

on:
  push:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    name: app' test
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.push.head.ref }}
      - name: automated tests
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci #cf. https://docs.npmjs.com/cli/v9/commands/npm-ci
      - run: npm run test

  # Build and publish the Docker image to the GCP Artifact Registry
  build-publish:
    needs: test
    runs-on: ubuntu-latest
    environment: staging
    name: build staging image and push it to GAR
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.push.head.ref }}
      - name: build code
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # Building the code
      - run: npm ci
      - run: npm run build
      # Login to GAR and pushing the image
      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.GAR_REGISTRY }}
          username: _json_key
          password: ${{ secrets.CLOUD_RUN_DEPLOYER_SA_KEY }}
      - run: docker build -t ${{ secrets.GAR_REPO }}/gcworkshop:${{ github.sha }} .
      - run: docker push ${{ secrets.GAR_REPO }}/gcworkshop:${{ github.sha }}

  deploy-to-cloud-run:
    needs: build-publish
    runs-on: ubuntu-latest
    environment: staging
    name: deploy the staging image to GCR
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.push.head.ref }}
      # Setup gcloud CLI
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.CLOUD_RUN_DEPLOYER_SA_KEY }}"
      # Deploy to Cloud Run
      - id: "deploy"
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: "gcworkshop"
          image: "${{ secrets.GAR_REPO }}/gcworkshop:${{ github.sha }}"
          env_vars: |
            NODE_ENV=staging
          flags: "--port=8080"
          region: "${{ secrets.CLOUD_RUN_REGION }}"
      - name: "deploy output"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
